### ISSUE TITLE
The Nines Error

### ISSUE THREAD

**Issue by chlohal** [nhs-t10/Robotics_2021_2022#24]
## What We Know about The Nines Error

- It is an `IndexOutOfBoundsException`
- It has this message: ```User code threw uncaught exception java.lang.IndexOutOfBoundsException: Index: 9, Size: 9```
- It happens in both Autoauto and teleop
- It is *not* triggered by any 1 control (we have tests for that)
- It is *not* triggered by any 2-control combo (we have tests for that)
- It does *not* happen instantly
- The index is *always* 9
- It happens in the main thread, *not* any other thread
- It's not caused by any literal 9s in the code

## What we Don't Know about The Nines Error

- Where it happens
- Is it an array? An arraylist? Something else that throws `IndexOutOfBoundsException`?
- Does it always happen eventually? Does it only happen sometimes?
- Why is it always nine????? Is nine important to the coding gods???

## What we Should Probably Do about The Nines Error

i mean fix it ig

**Comment by moekofi** [comment]
**NEW INFORMATION ABOUT THE NINES ERROR**

The nines error is something to do with the hardwaremap/manipulation manager OR the omnidrive

This conclusions was reached due to multiple factors:

- The nines error happens during teleop, after init
- the only lines of code in teleop's loop is inputs, omnidrive, and telemetry
- inputs is not the issue, because inputs are not used in autonomous
- Telemetry is not the issue, because telemetry uses a hashmap, not an array
- The only line of code left is `driver.driveOmni(input.getFloatArrayOfInput("drivingControls"));` 
- Furthermore, we know we have exactly 9 hardware devices

When looking for the error, look for a situation where the hardwaremap, manipulation manager, and/or the omnidrive code (specifically omnidrive!) tries to access an array index.

**Comment by chlohal** [comment]
We haven't seen this for like... a month. I'm gonna close it as `couldnt-reproduce` for now.
